name: Day 2 - First Pipeline

on:
  push:
    branches:
      - main

jobs:
  hello-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print message
        run: echo "Hello nit, your pipeline is working!"

      - name: Show current directory
        run: pwd

      - name: List files
        run: ls -la
